using System.Text.Json;
using System.Text.Json.Serialization;

namespace SpaceSails.Core;

// ─────────────────────────────────────────────────────────────────────────────────────────────────
// Ten vaults and an honest door (#310). The personal vault (#225) round-trips ONE life; this is the
// bookshelf that holds many. The design law:
//   * The vault payload itself is UNTOUCHED — each slot stores a byte-for-byte VaultSerializer string,
//     so the determinism/lossless law (Vault.cs) still holds per slot. This file only manages WHICH
//     slot, and the human-readable LABEL beside each (where/when/build stamp).
//   * ONE rolling AUTOSAVE slot follows the ship (rewritten on every durable event, exactly as the
//     single-slot autosave did) so Continue is always current — "where I actually am" (owner's law).
//   * NINE MANUAL slots the captain banks deliberately (pre-haul, pre-bury, pre-aerobrake — the vault
//     moments) — never touched by the autosave, so a deliberate bank is safe from the rolling save.
//   * A tiny MANIFEST (this file's JSON) carries only the labels; the heavy vault JSON lives under a
//     per-slot key, so a rolling autosave rewrites one slot, not the whole book.
//
// THE MARS-PULL ROOT CAUSE this replaces (issue #310): the old system had exactly ONE key
// (spacesails.vault.v1). The rolling autosave, a fresh scenario start, and Continue ALL read/wrote
// that single key. So once ANY non-Continue path wrote it — an accidental "Rusty Roadstead — docked"
// scenario pick at the (unresponsive) boot picker, or any durable event after such a pick — the
// Uranus/The-Tilt autosave was overwritten and GONE. With one slot, Continue can only ever offer "the
// last thing written", which is why it kept waking at Mars. Separating the rolling autosave from
// deliberate scenario starts, and giving Continue its own always-current slot, is the fix.
// ─────────────────────────────────────────────────────────────────────────────────────────────────

/// <summary>Which kind of slot: the one rolling autosave that follows the ship, or a manual bank.</summary>
public enum SaveSlotKind
{
    /// <summary>The single rolling autosave — rewritten on every durable event; Continue reads it.</summary>
    Autosave,

    /// <summary>A deliberately-banked slot; never overwritten by the autosave.</summary>
    Manual,
}

/// <summary>
/// One slot's label — everything the picker shows beside it. NOT the vault payload (that rides its own
/// per-slot key, byte-for-byte a <see cref="VaultSerializer"/> string). WHERE + WHEN + build stamp, plus
/// a monotonic <see cref="SavedRealTicks"/> so "Continue = newest" is an exact, tie-free comparison.
/// </summary>
public sealed record SaveSlotMeta
{
    public string Id { get; init; } = "";
    public SaveSlotKind Kind { get; init; } = SaveSlotKind.Manual;

    /// <summary>Human WHERE: the berth name when docked, or "adrift near &lt;body&gt;" when saved in flight
    /// (VaultResume's nearest-haven), or "unknown waters" when the vault carried no resume section.</summary>
    public string Where { get; init; } = "";

    /// <summary>True when the save happened clamped on (WHERE is a real berth); false = adrift/nearest.</summary>
    public bool WasDocked { get; init; }

    /// <summary>Sim clock (seconds) at save — the same value the resume ephemeris keys off.</summary>
    public double SavedSimTime { get; init; }

    /// <summary>Sim day (0-based), the game's own clock unit (see Map's "day N" convention).</summary>
    public int SimDay { get; init; }

    /// <summary>Real wall-clock label at save, e.g. "2026-07-18 21:40" — the "when in MY life" stamp.</summary>
    public string RealTimeLabel { get; init; } = "";

    /// <summary>Monotonic real-time tick at save (<c>DateTimeOffset.UtcNow.UtcTicks</c>). The tie-free key
    /// for "newest" — Continue resumes the slot with the greatest value (autosave, as it plays).</summary>
    public long SavedRealTicks { get; init; }

    /// <summary>The build stamp (#254) that wrote the slot — "am I even looking at the same build?".</summary>
    public string BuildStamp { get; init; } = "";

    /// <summary>Mirror of <see cref="Vault.Tampered"/> at save time, so the picker can mark it.</summary>
    public bool Tampered { get; init; }

    // ── #948 · The human half of the row. Owner, looking at eight identical berths: "Let's have an option to
    //    change the name of our avatar. It solves the issue of forgetting who you are amongst the autogenerated
    //    names", and "I would like to save this point with a comment field and a captain's name of my whim."
    //    Additive manifest data (the JSON is tolerant): a slot banked before #948 reads all three back as ""
    //    and the row falls back to the seeded captain and DefaultTitle. Mirrored from the payload's own
    //    LogbookSection so the row and the exported file can never disagree.

    /// <summary>The captain's name at the moment of saving — the renamed one, or the seeded roster name.
    /// Blank on a pre-#948 slot; the caller re-derives the seeded name from the thread id.</summary>
    public string CaptainName { get; init; } = "";

    /// <summary>The captain's-whim title for this moment. Blank = untitled; the row shows
    /// <see cref="SaveSlotLabels.DefaultTitle"/> instead.</summary>
    public string Title { get; init; } = "";

    /// <summary>What the captain was doing when they kept this moment. Free text, never parsed.</summary>
    public string Note { get; init; } = "";
}

/// <summary>Pure label helpers — the WHERE line, derived from a loaded <see cref="Vault"/>. Kept here (not
/// in the client) so the slot label is a tested truth, not a razor accident.</summary>
public static class SaveSlotLabels
{
    /// <summary>The WHERE string for a vault: a berth name when docked, "adrift near X" when the save
    /// happened in flight (nearest-haven resume), or "unknown waters" when there is no resume section.</summary>
    public static string Where(Vault? vault)
    {
        ResumeSection? resume = vault?.Resume;
        if (resume is null || string.IsNullOrWhiteSpace(resume.HavenName))
        {
            return "unknown waters";
        }

        return resume.WasDocked ? resume.HavenName : $"adrift near {resume.HavenName}";
    }

    /// <summary>The label an import screen shows, read STRAIGHT FROM the file's contents (never the
    /// filename — a renamed file still identifies itself). WHERE + sim day + the tampered mark, all from
    /// the vault payload. Real-time/build-stamp are left blank: they live in the slot manifest, not the
    /// portable file, so a file preview honestly shows only what the file itself carries.</summary>
    public static SaveSlotMeta PreviewMeta(Vault? vault) => new()
    {
        Kind = SaveSlotKind.Manual,
        Where = Where(vault),
        WasDocked = vault?.Resume?.WasDocked ?? false,
        SavedSimTime = vault?.SavedSimTime ?? 0,
        SimDay = (int)((vault?.SavedSimTime ?? 0) / 86400),
        Tampered = vault?.Tampered ?? false,
        // #948 — a file names its own captain and carries its own page, so an import preview can say WHOSE
        // moment it is before the captain commits to boarding it. A pre-#948 file has no logbook: blanks.
        CaptainName = CleanName(vault?.Logbook?.CaptainName),
        Title = CleanTitle(vault?.Logbook?.Title),
        Note = CleanNote(vault?.Logbook?.Note),
    };

    // ── #948 · titles and notes: the one place their shape is decided. ──

    /// <summary>How long a captain's-whim title may be before the row stops being a row.</summary>
    public const int MaxTitleLength = 80;

    /// <summary>How long a note may be. Generous — it is a paragraph about what you were doing, not a
    /// tweet — but bounded, because it rides in localStorage beside nine other slots.</summary>
    public const int MaxNoteLength = 600;

    /// <summary>Tidy a typed title: trim, collapse every run of whitespace (newlines included — a title is
    /// ONE line), and cut to <see cref="MaxTitleLength"/>. Null/blank comes back "" (= untitled).</summary>
    public static string CleanTitle(string? title) => Tidy(title, MaxTitleLength, oneLine: true);

    /// <summary>Tidy a typed note: trim and cut to <see cref="MaxNoteLength"/>, but KEEP the line breaks —
    /// a note is allowed to be a paragraph. Null/blank comes back "".</summary>
    public static string CleanNote(string? note) => Tidy(note, MaxNoteLength, oneLine: false);

    /// <summary>Tidy a captain's name the same way a title is tidied, at the roster's own length.</summary>
    public static string CleanName(string? name) => Tidy(name, Captains.MaxNameLength, oneLine: true);

    private static string Tidy(string? text, int max, bool oneLine)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return "";
        }

        string t = text;
        if (oneLine)
        {
            var sb = new System.Text.StringBuilder(t.Length);
            bool pendingSpace = false;
            foreach (char c in t)
            {
                if (char.IsWhiteSpace(c))
                {
                    pendingSpace = sb.Length > 0;
                    continue;
                }

                if (pendingSpace)
                {
                    sb.Append(' ');
                    pendingSpace = false;
                }

                sb.Append(c);
            }

            t = sb.ToString();
        }
        else
        {
            t = t.Trim();
        }

        return t.Length > max ? t[..max].TrimEnd() : t;
    }

    /// <summary>The title a save gets when nobody typed one: <c>&lt;captain&gt; — &lt;place&gt; — day N</c>
    /// (the default the bank dialog offers, and the fallback a row shows for an untitled slot). Every part is
    /// optional — a nameless captain, an unknown place and a day zero all still make a readable line.</summary>
    public static string DefaultTitle(string? captainName, string? where, int simDay)
    {
        string captain = CleanName(captainName);
        string place = string.IsNullOrWhiteSpace(where) ? "unknown waters" : where.Trim();
        string day = $"day {Math.Max(0, simDay)}";
        string head = captain.Length > 0 ? $"{captain} — {place}" : place;
        return CleanTitle($"{head} — {day}");
    }

    /// <summary>The title to PRINT on a slot row: the captain's own, when they gave one; otherwise the
    /// derived <see cref="DefaultTitle"/> built from that slot's own captain, place and day. One truth, so
    /// the drawer, the front door and the export filename cannot drift apart.</summary>
    public static string TitleOf(SaveSlotMeta meta)
    {
        ArgumentNullException.ThrowIfNull(meta);
        string given = CleanTitle(meta.Title);
        return given.Length > 0 ? given : DefaultTitle(meta.CaptainName, meta.Where, meta.SimDay);
    }
}

/// <summary>
/// Filesystem-safe export filenames, spun from the SAME label machinery the slots show (#312). One
/// truth: the harbor in the filename IS the <see cref="SaveSlotLabels.Where"/> line, slugged. Ends the
/// browser's <c>spacesails-vault (5).json</c> roulette — the file names the place it was saved at.
/// Shape: <c>spacesails-&lt;place-slug&gt;-day&lt;N&gt;-&lt;yyyy-MM-dd-HHmm&gt;.json</c>,
/// e.g. <c>spacesails-the-tilt-day34-2026-07-18-1022.json</c>.
/// </summary>
public static class SaveFileNames
{
    /// <summary>Slug a WHERE line into a filesystem-safe token: lower-case ASCII letters/digits, every
    /// run of anything else collapsed to a single dash, ends trimmed. "adrift near The Tilt" →
    /// "adrift-near-the-tilt"; "The Tilt" → "the-tilt"; empty/exotic → "voyage".</summary>
    public static string Slug(string? where)
    {
        if (string.IsNullOrWhiteSpace(where))
        {
            return "voyage";
        }

        var sb = new System.Text.StringBuilder(where.Length);
        bool pendingDash = false;
        foreach (char c in where.ToLowerInvariant())
        {
            if (char.IsAsciiLetterOrDigit(c))
            {
                if (pendingDash && sb.Length > 0)
                {
                    sb.Append('-');
                }

                sb.Append(c);
                pendingDash = false;
            }
            else
            {
                pendingDash = true;
            }
        }

        return sb.Length == 0 ? "voyage" : sb.ToString();
    }

    /// <summary>The export filename for a slot's (or the live moment's) label — the one true filename
    /// builder. Reads WHERE, the sim day, and the real-time stamp reconstructed from the label's
    /// monotonic tick, so a per-slot export names the SLOT's state and a live export names THIS moment.</summary>
    public static string ForMeta(SaveSlotMeta meta)
    {
        ArgumentNullException.ThrowIfNull(meta);
        DateTimeOffset realTime = meta.SavedRealTicks > 0
            ? new DateTimeOffset(meta.SavedRealTicks, TimeSpan.Zero)
            : DateTimeOffset.UtcNow;
        return For(meta.Where, meta.SimDay, realTime);
    }

    /// <summary>Build the filename from its parts: <c>spacesails-&lt;place&gt;-day&lt;N&gt;-&lt;stamp&gt;.json</c>.</summary>
    public static string For(string? where, int simDay, DateTimeOffset realTime)
    {
        string place = Slug(where);
        int day = Math.Max(0, simDay);
        string stamp = realTime.ToString("yyyy-MM-dd-HHmm", System.Globalization.CultureInfo.InvariantCulture);
        return $"spacesails-{place}-day{day}-{stamp}.json";
    }
}
