using System;
using System.Collections.Generic;

namespace SpaceSails.Core;

/// <summary>
/// #592/#677 · EVERY FLOOR A SITE ACTUALLY HAS, and the arithmetic of the shafts that reach them —
/// the listed floors, then the gap where nothing was dug, then the band nobody listed, then the band
/// of nothing under THAT, then the galleries nobody dug at all.
///
/// <para>The band is the unit of descent: <see cref="FloorsPerShaft"/> floors to a shaft, one shaft
/// advertised at a time, and a band bottom is where the panel stops offering a button. Everything
/// that walks the building — the lift, the stair, the nearest-floor fallback — asks here.</para>
///
/// <para>Split out of <c>UndergroundComplex.cs</c> under #251 with no member renamed, re-scoped or
/// re-ordered.</para>
/// </summary>
public static partial class UndergroundComplex
{
    /// <summary>#592/#677 · EVERY FLOOR THIS SITE ACTUALLY HAS, top to bottom — the listed ones, then the gap
    /// where nothing was dug, then the band nobody listed, then the band of nothing under THAT, then the
    /// galleries nobody dug at all.
    ///
    /// <para>The one place that knows the shape. Audits, the renderer and the labs all walk this rather
    /// than counting from a depth, because with a gap in the middle "−1 down to the bottom" is no longer
    /// the floor list — and a phantom floor generated by an audit is a topology nobody ships being checked
    /// instead of the one they do.</para></summary>
    public static IEnumerable<int> FloorsOf(string bodyId)
    {
        ArgumentNullException.ThrowIfNull(bodyId);
        for (int level = -1; level >= DepthOf(bodyId); level--)
        {
            yield return level;
        }

        if (!HasUnlistedBand(bodyId))
        {
            yield break;
        }
        int band = UnlistedBandOf(bodyId);
        for (int level = BandTop(band); level >= BandBottom(band); level--)
        {
            yield return level;
        }

        if (!HasFoundBand(bodyId))
        {
            yield break;
        }
        int found = FoundBandOf(bodyId);
        for (int level = BandTop(found); level >= BandBottom(found); level--)
        {
            yield return level;
        }
    }

    /// <summary>#677 · THE NEXT SHAFT THAT EXISTS below this floor, or null where there is none.
    ///
    /// <para>Everything that used to ask <c>BandOf(level) + 1</c> asks this instead, and the reason is the
    /// band of nothing: the band immediately under the one nobody listed has no floors in it at all, so a
    /// card minted for "the next band" would authorise a hole nobody dug and the panel would offer a button
    /// to rock. One walk over <see cref="SiteHasBand"/>, in one place, rather than two callers each teaching
    /// themselves the shape of a building that now has two gaps in it.</para></summary>
    public static int? NextShaftBelow(string bodyId, int level)
    {
        ArgumentNullException.ThrowIfNull(bodyId);
        int last = BandOf(DeepestPossibleFloor);
        for (int band = BandOf(Math.Min(level, -1)) + 1; band <= last; band++)
        {
            if (SiteHasBand(bodyId, band))
            {
                return band;
            }
        }
        return null;
    }

    /// <summary>#677 · The real floor a caller asking for <paramref name="wanted"/> should be put on: the
    /// floor of this site nearest to it, and never a floor in a gap where nothing was dug.
    ///
    /// <para>Written here because the dev floor cheat used to do this arithmetic itself — clamp to the true
    /// depth, then snap into the unlisted band's head — which is a caller reasoning about the shape of a
    /// building it does not own (§13.15's second cause). It was right about a building with one gap in it
    /// and would have set a captain down in solid rock the day there were two. Ties go DEEPER, because a
    /// cheat asking for a floor between two buildings is asking for the lower one.</para></summary>
    public static int NearestFloorTo(string bodyId, int wanted)
    {
        ArgumentNullException.ThrowIfNull(bodyId);
        int best = -1;
        int bestGap = int.MaxValue;
        foreach (int level in FloorsOf(bodyId))
        {
            int gap = Math.Abs(level - wanted);
            if (gap <= bestGap)
            {
                bestGap = gap;
                best = level;
            }
        }
        return best;
    }

    /// <summary>#585 · THE SHAFTS ARE THE LIMIT — the owner's own observation, turned into the mechanic.
    ///
    /// <para>A single lift never serves a whole facility: it serves a BAND. Reach the bottom of a band and the
    /// car goes no further; the way down is a different shaft, somewhere on that floor, which you have to
    /// find. That is what keeps unlimited depth from being an unlimited corridor — the descent is gated by
    /// exploring rather than by a number, and it is how a building this size would really be dug.</para></summary>
    public const int FloorsPerShaft = 4;

    /// <summary>Which shaft band a floor belongs to. Band 0 is the one the surface lift head serves.</summary>
    public static int BandOf(int level) => (-level - 1) / FloorsPerShaft;

    /// <summary>The deepest floor a shaft band reaches, never past the bottom of the building that band
    /// belongs to.
    ///
    /// <para>#592 · Two buildings, so two bottoms. Every band the site admits to stops at the LISTED depth —
    /// that is what makes the last listed floor feel like the bottom, because for that shaft it is. The
    /// band nobody listed is a whole band of its own, below a GAP where nothing was dug, and it stops at
    /// its own.</para></summary>
    public static int BandFloor(string bodyId, int band)
    {
        ArgumentNullException.ThrowIfNull(bodyId);
        int listed = DepthOf(bodyId);
        return band > BandOf(listed)
            ? BandBottom(band)                          // the unlisted band, on its own shaft
            : Math.Max(listed, BandBottom(band));       // everything the directory knows about
    }

    /// <summary>Is this the floor where the car stops and you go looking for the next shaft?</summary>
    public static bool IsBandBottom(string bodyId, int level) =>
        level == BandFloor(bodyId, BandOf(level)) && level > TrueDepthOf(bodyId);
}
