namespace SpaceSails.Core;

// ─── VAULT SECTIONS: THE ORGANISATIONS, AND THE ROW IN THE SLOT LIST (#225) ───
//
// What the authorities have on file, what KAAMOS and Nebula know, the berth the resume docks at, and the
// logbook page that names the save in the slot list.
// 
// Split out of Vault.cs under #251 — whole record types moved, nothing inside one re-ordered.

public sealed record AuthoritiesSection
{
    /// <summary>Card ids, in whatever order they were written.</summary>
    public IReadOnlyList<string> Cards { get; init; } = [];
}

// ── PROJEKTI KAAMOS (#411): the ice-moon mystery, assembled per-thread. ──

/// <summary>The KAAMOS lore-fragments this universe's captain has assembled (#411) — stored as the flat
/// list of fragment ids, the minimal shape (<see cref="KaamosProgress.AssembledIds"/>), so the reach
/// logic and the text both rebuild from the pool at load rather than the save carrying prose. Its own
/// independently-optional section: a pre-#411 file simply lacks it and defaults to nothing assembled (a
/// captain who has heard nothing of the polar night). Unknown-to-the-pool ids are dropped on load, so
/// the round-trip is always re-readable against the pool that wrote it.</summary>
public sealed record KaamosSection
{
    /// <summary>The assembled fragment ids (see <see cref="KaamosLore.Fragments"/>). Order is not
    /// meaningful — assembly is a set — but the writer emits canonical order for a stable file.</summary>
    public IReadOnlyList<string> AssembledFragmentIds { get; init; } = [];

    /// <summary>#635 · Whether this captain has had a filing for the sealed ice-moon berth returned by the
    /// board — the arc's front door, and not a fragment: it credits nothing toward the gate. Its own flag
    /// rather than a pool id, because the pool is the thing the reach logic counts and a phantom id in it
    /// would be exactly the drift <see cref="KaamosProgress.Assemble"/> refuses. A save written before
    /// #635 simply lacks the property and defaults to false.</summary>
    public bool BerthFilingBounced { get; init; }
}

// ── NEBULA MUTUAL (#422): the second story arc, the truth behind the player's own deaths, per-thread. ──

/// <summary>The NEBULA lore-fragments this universe's captain has assembled about what their resurrections
/// really are (#422) — stored as the flat list of fragment ids (<see cref="NebulaProgress.AssembledIds"/>)
/// plus the one-time convergence-reveal bit, so the fine-print logic and the text both rebuild from the pool
/// at load rather than the save carrying prose. Its own independently-optional section: a pre-#422 file
/// simply lacks it and defaults to nothing assembled and the convergence unseen (a captain who has died and
/// come back and never once wondered why). Unknown-to-the-pool ids are dropped on load, so the round-trip is
/// always re-readable against the pool that wrote it.</summary>
public sealed record NebulaSection
{
    /// <summary>The assembled fragment ids (see <see cref="NebulaLore.Fragments"/>). Order is not meaningful —
    /// assembly is a set — but the writer emits canonical order for a stable file.</summary>
    public IReadOnlyList<string> AssembledFragmentIds { get; init; } = [];

    /// <summary>True once the one-time CONVERGENCE reveal has fired for this thread
    /// (<see cref="ArcConvergence"/>). Persisted so the biggest #391 throw plays once in a universe and never
    /// re-fires on a reload — the analog of <see cref="NerveSection.MonolithSeen"/>. Defaults false (a pre-#422
    /// file, or one saved before the two arcs met).</summary>
    public bool ConvergenceSeen { get; init; }
}

// ── The resume berth (owner's law): where the pirate wakes, always docked. ──

/// <summary>The berth to resume at: the last-docked haven, or the nearest dockable haven computed at
/// save time if the save happened in flight. Loading rebuilds the ship DOCKED here at load-time
/// ephemeris — no stored orbit, ever. <see cref="WasDocked"/> records which case produced it (for the
/// picker's honesty and for tests).</summary>
public sealed record ResumeSection
{
    public string HavenId { get; init; } = "";
    public string HavenName { get; init; } = "";
    /// <summary>True if the save happened while docked/clamped at this berth; false if the ship was in
    /// flight and this is the nearest dockable haven chosen at save time.</summary>
    public bool WasDocked { get; init; }
}

// ── #948 · The logbook page: the human half of a save. ──

/// <summary>
/// #948 · THE PAGE THE CAPTAIN WROTE. Owner, at the logbook with eight identical berths open: <i>"Let's have
/// an option to change the name of our avatar. It solves the issue of forgetting who you are amongst the
/// autogenerated names"</i>, and <i>"I would like to save this point with a comment field and a captain's
/// name of my whim."</i>
///
/// <para>Three strings, and every one of them is the player's, not the generator's: the CAPTAIN'S NAME (the
/// seeded roster name until they change it — see <see cref="Captains.CleanName"/>), the TITLE they gave this
/// moment, and the NOTE about what they were doing when they kept it. Rides IN the vault payload, not merely
/// beside it in the slot manifest, so an exported .json carries the name and the note to whatever machine
/// opens it next (<see cref="VaultSerializer.StampLogbook"/> writes it onto an already-banked payload without
/// disturbing a single other byte of the save).</para>
/// </summary>
public sealed record LogbookSection
{
    /// <summary>The captain's name at the moment of saving — the renamed one if the player renamed them,
    /// else the seeded roster name. Blank on a pre-#948 file; the game then re-derives the seeded name.</summary>
    public string CaptainName { get; init; } = "";

    /// <summary>The captain's-whim title for THIS moment ("the run before the Kaamos dive"). Blank means
    /// nobody titled it, and the row falls back to <see cref="SaveSlotLabels.DefaultTitle"/>.</summary>
    public string Title { get; init; } = "";

    /// <summary>Free text: what they were doing, what they meant to do next, who they must not meet again.
    /// Blank means no note was written. Never parsed by the game — it is for the human alone.</summary>
    public string Note { get; init; } = "";
}
