namespace SpaceSails.Core.Tests;

/// <summary>
/// #948 / #951 · I WANT THIS MOMENT — the model behind a save the captain named.
///
/// <para>Owner, at the logbook with the export button under his cursor (2026-08-21): <i>"Here I can export
/// the game situation as file... but I would like to save this point with a comment field and a captain's
/// name of my whim. <b>I want this moment, not that I die and that situation overwrites this.</b>"</i> And,
/// at the front door reading six generated names one under the other: <i>"Let's have an option to change the
/// name of our avatar. It solves the issue of forgetting who you are amongst the autogenerated names."</i></para>
///
/// <h3>What is actually being pinned</h3>
/// <para>Four laws, and the fourth is the one the owner was frightened about:</para>
/// <list type="number">
///   <item>A title and a note SURVIVE — in the slot's label AND inside the vault payload, so an exported
///   .json carries them to a machine that has never heard of this thread.</item>
///   <item>A captain's name is EDITABLE and STICKS: the rename writes the row, the autosave preserves it
///   (<see cref="GameThreadRegistry.Touch"/> has always preserved the identity — this proves a RENAMED one
///   survives too), and blank restores the generator.</item>
///   <item>An OLD file — one written before any of this existed — still loads, and reads back with blanks
///   rather than throwing or losing its other sections.</item>
///   <item><b>The autosave never overwrites a bank.</b> This was already the law (#310 gave the rolling save
///   its own slot); it had never been PINNED against the exact sequence the owner feared — bank a moment,
///   then die, then let the autosave run. Proven byte-for-byte, payload and label both.</item>
/// </list>
///
/// <h3>Proven red on purpose</h3>
/// <para>Every guard here was watched failing before it was trusted, by reverting the fix under it:</para>
/// <list type="bullet">
///   <item>Dropping <c>logbook</c> from <see cref="VaultSerializer"/>'s section list fails
///   <c>THE_PAGE_RidesInTheFileItself</c> (title/note come back "" through a round-trip).</item>
///   <item>Implementing <see cref="VaultSerializer.StampLogbook"/> as the obvious Load-then-Save round-trip
///   instead of JSON surgery fails <c>THE_PAGE_StampingItDisturbsNothingElse</c> — an unknown forward-compat
///   section is silently dropped by the per-section harvest, which is exactly the trap.</item>
///   <item>Letting <see cref="GameThreadRegistry.Touch"/> re-seed the name (drop its <c>existing?.CaptainName</c>
///   branch) fails <c>THE_NAME_AnAutosaveDoesNotUnnameYou</c>.</item>
///   <item>Pointing the autosave at the manual slot id — the pre-#310 single-key behaviour, the actual Mars
///   bug — fails <c>THE_FEAR_DyingDoesNotOverwriteAMomentYouBanked</c> on the first assert.</item>
/// </list>
/// </summary>
public class IWantThisMomentTests
{
    // A dictionary-backed store: the whole book is browserless and deterministic.
    private sealed class MemStore : ISlotStore
    {
        private readonly Dictionary<string, string> _map = new(StringComparer.Ordinal);
        public string? Read(string key) => _map.TryGetValue(key, out string? v) ? v : null;
        public void Write(string key, string value) => _map[key] = value;
        public void Clear(string key) => _map.Remove(key);
    }

    private static Vault VaultAt(string haven, bool docked, double simTime, LogbookSection? page = null) => new()
    {
        SavedSimTime = simTime,
        Purse = new PurseSection(4_211),
        Caches = new CachesSection
        {
            Caches = [new CacheRecord { Id = "cache-1", BodyId = "the-ice", LandmarkName = "Kaamos shelf", Coin = 900, PlayerOwned = true }],
        },
        Resume = new ResumeSection { HavenId = haven.ToLowerInvariant(), HavenName = haven, WasDocked = docked },
        Logbook = page,
    };

    private static SaveSlotMeta MetaFor(Vault v, SaveSlotKind kind, long ticks) => new()
    {
        Kind = kind,
        Where = SaveSlotLabels.Where(v),
        WasDocked = v.Resume?.WasDocked ?? false,
        SavedSimTime = v.SavedSimTime,
        SimDay = (int)(v.SavedSimTime / 86400),
        RealTimeLabel = "2026-08-21 16:43",
        SavedRealTicks = ticks,
        BuildStamp = "build d1fbc0c",
        Tampered = v.Tampered,
        CaptainName = SaveSlotLabels.CleanName(v.Logbook?.CaptainName),
        Title = SaveSlotLabels.CleanTitle(v.Logbook?.Title),
        Note = SaveSlotLabels.CleanNote(v.Logbook?.Note),
    };

    // ─────────────────────────────────────────────────────────────────────────────────────────────
    // 1 · THE PAGE — a title and a note, and they ride in the file, not only beside it.
    // ─────────────────────────────────────────────────────────────────────────────────────────────

    [Fact]
    public void THE_PAGE_RidesInTheFileItself()
    {
        var page = new LogbookSection
        {
            CaptainName = "Captain Erno of the Long Ear",
            Title = "The run before the ice",
            Note = "Full hold, one collector three days behind. Do NOT dock at The Red Eye.",
        };

        Vault loaded = VaultSerializer.Load(VaultSerializer.Save(VaultAt("The Tilt", docked: true, 192 * 86400, page)));

        Assert.False(loaded.Tampered);
        Assert.Equal("Captain Erno of the Long Ear", loaded.Logbook?.CaptainName);
        Assert.Equal("The run before the ice", loaded.Logbook?.Title);
        Assert.Equal("Full hold, one collector three days behind. Do NOT dock at The Red Eye.", loaded.Logbook?.Note);
    }

    [Fact]
    public void THE_PAGE_AnOldFileWithoutOneStillLoads()
    {
        // A save written before #948: no logbook section anywhere in it. It must load its OTHER sections
        // exactly as it always did, come back with a null page, and NOT be marked tampered — an old file is
        // not an edited file.
        string old = VaultSerializer.Save(VaultAt("Selene Gate", docked: true, 12 * 86400, page: null));
        Assert.DoesNotContain("logbook", old, StringComparison.OrdinalIgnoreCase);

        Vault loaded = VaultSerializer.Load(old);

        Assert.False(loaded.Tampered);
        Assert.Null(loaded.Logbook);
        Assert.Equal(4_211, loaded.Purse?.Credits);
        Assert.Equal("Selene Gate", loaded.Resume?.HavenName);

        // And the row it makes reads honestly: blanks, and a derived title rather than an empty headline.
        SaveSlotMeta preview = SaveSlotLabels.PreviewMeta(loaded);
        Assert.Equal("", preview.Title);
        Assert.Equal("", preview.Note);
        Assert.Equal("", preview.CaptainName);
        Assert.Equal("Selene Gate — day 12", SaveSlotLabels.TitleOf(preview));
    }

    [Fact]
    public void THE_PAGE_StampingItDisturbsNothingElse()
    {
        // The trap this method exists to avoid: rewriting a title by Load-then-Save would silently DROP any
        // section this build cannot name, because the harvest is per-section and by name. So a file is given
        // a section from the future, its page is rewritten, and the future section must still be there —
        // with a checksum that still validates, so a retitled save is not slandered as tampered.
        string original = VaultSerializer.Save(VaultAt("The Rusty Roadstead", docked: true, 40 * 86400));
        System.Text.Json.Nodes.JsonNode root = System.Text.Json.Nodes.JsonNode.Parse(original)!;
        root["sections"]!["somethingFromTheFuture"] = System.Text.Json.Nodes.JsonNode.Parse("""{"kept":true}""");
        // Re-stamp the checksum so the doctored file starts out honest (StampLogbook rewrites it anyway).
        string withFuture = VaultSerializer.StampLogbook(root.ToJsonString(), new LogbookSection());

        string stamped = VaultSerializer.StampLogbook(withFuture, new LogbookSection
        {
            CaptainName = "Captain Nemo",
            Title = "Before the dive",
            Note = "third time down",
        });

        Assert.Contains("somethingFromTheFuture", stamped, StringComparison.Ordinal);

        Vault after = VaultSerializer.Load(stamped);
        Assert.False(after.Tampered);                          // the checksum was recomputed, not orphaned
        Assert.Equal("Before the dive", after.Logbook?.Title);
        Assert.Equal("third time down", after.Logbook?.Note);
        Assert.Equal(4_211, after.Purse?.Credits);             // every other section untouched
        Assert.Equal("The Rusty Roadstead", after.Resume?.HavenName);
        Assert.Single(after.Caches!.Caches);
    }

    [Fact]
    public void THE_PAGE_IsEditableInPlaceAndTakesNoNewSave()
    {
        var book = new SaveSlotBook(new MemStore(), "thread-a");
        Vault banked = VaultAt("The Tilt", docked: true, 88 * 86400);
        string payload = VaultSerializer.Save(banked);
        book.Save("3", payload, MetaFor(banked, SaveSlotKind.Manual, ticks: 1_000));

        book.Retitle("3", "  The night   the lift only went   down  ", "Owner found it in a playtest.\nSee #600.");

        SaveSlotMeta after = book.Get("3")!;
        Assert.Equal("The night the lift only went down", after.Title);      // one line, runs collapsed
        Assert.Equal("Owner found it in a playtest.\nSee #600.", after.Note); // a note keeps its paragraphs
        Assert.Equal(1_000, after.SavedRealTicks);                            // NOT a save: the clock did not move
        Assert.Equal(88 * 86400, after.SavedSimTime);

        // And it reached the payload too, so an export from this berth carries the page with it.
        Vault reread = VaultSerializer.Load(book.ReadPayload("3")!);
        Assert.False(reread.Tampered);
        Assert.Equal("The night the lift only went down", reread.Logbook?.Title);
        Assert.Equal(4_211, reread.Purse?.Credits);
    }

    [Fact]
    public void THE_PAGE_AnUntitledRowStillNamesItself()
    {
        // The default the bank sheet offers, and the fallback an untitled row prints: one derivation, so the
        // drawer and the front door cannot drift apart.
        Assert.Equal(
            "Captain Mabel Vane — adrift near The Tilt — day 192",
            SaveSlotLabels.DefaultTitle("Captain Mabel Vane", "adrift near The Tilt", 192));

        // Every part is optional and none of them may produce a blank headline.
        Assert.Equal("unknown waters — day 0", SaveSlotLabels.DefaultTitle(null, null, 0));
        Assert.Equal("unknown waters — day 0", SaveSlotLabels.DefaultTitle("   ", "  ", -5));

        // A given title wins; a blank one falls through to the derivation.
        var titled = new SaveSlotMeta { Title = "Before the ice", CaptainName = "Captain Nemo", Where = "The Tilt", SimDay = 9 };
        Assert.Equal("Before the ice", SaveSlotLabels.TitleOf(titled));
        Assert.Equal("Captain Nemo — The Tilt — day 9", SaveSlotLabels.TitleOf(titled with { Title = "   " }));
    }

    [Fact]
    public void THE_PAGE_IsBoundedSoARowStaysARow()
    {
        string longTitle = new('x', SaveSlotLabels.MaxTitleLength + 200);
        string longNote = new('y', SaveSlotLabels.MaxNoteLength + 200);
        Assert.Equal(SaveSlotLabels.MaxTitleLength, SaveSlotLabels.CleanTitle(longTitle).Length);
        Assert.Equal(SaveSlotLabels.MaxNoteLength, SaveSlotLabels.CleanNote(longNote).Length);
        Assert.Equal(Captains.MaxNameLength, Captains.CleanName(new string('z', 400)).Length);

        // A title is ONE line even when it is typed as three.
        Assert.Equal("one two three", SaveSlotLabels.CleanTitle("one\ntwo\r\n   three  "));
    }

    // ─────────────────────────────────────────────────────────────────────────────────────────────
    // 2 · THE NAME — a captain of your own whim, and it survives everything that touches the row.
    // ─────────────────────────────────────────────────────────────────────────────────────────────

    [Fact]
    public void THE_NAME_IsYoursToGiveAndToTakeBack()
    {
        var reg = new GameThreadRegistry(new MemStore());
        reg.Touch("universe-1", "The Tilt", 3, ticks: 500);
        string seeded = Captains.Name("universe-1");

        GameThreadInfo renamed = reg.Rename("universe-1", "  Captain   Erno  of the  Long Ear ")!;
        Assert.Equal("Captain Erno of the Long Ear", renamed.CaptainName);
        Assert.Equal("Captain Erno of the Long Ear", Captains.For(reg.Get("universe-1")!).Name);

        // "Updatable" includes updating it back: a blank name restores the generator's.
        Assert.Equal(seeded, reg.Rename("universe-1", "   ")!.CaptainName);

        // Renaming does not move a universe in the world: no clock is bumped, and it does not become active.
        Assert.Equal(500, reg.Get("universe-1")!.LastActiveTicks);
        Assert.Null(reg.Rename("no-such-thread", "Ghost"));
    }

    [Fact]
    public void THE_NAME_AnAutosaveDoesNotUnnameYou()
    {
        // The rename is worth nothing if the next durable event re-seeds it. Touch has always preserved the
        // stored identity (like the born-on stamp); this pins that a RENAMED one is preserved by the same
        // branch — and that the retired-captain history and the born-on tick ride through with it.
        var reg = new GameThreadRegistry(new MemStore());
        reg.Touch("universe-2", "Selene Gate", 0, ticks: 100);
        reg.Rename("universe-2", "Captain Erno");

        reg.Touch("universe-2", "adrift near Luna", 1, ticks: 200);
        reg.Touch("universe-2", "The Red Eye", 4, ticks: 300);

        GameThreadInfo row = reg.Get("universe-2")!;
        Assert.Equal("Captain Erno", row.CaptainName);
        Assert.Equal(100, row.CreatedTicks);
        Assert.Equal(300, row.LastActiveTicks);
        Assert.Equal("The Red Eye", row.Where);
    }

    [Fact]
    public void THE_NAME_TravelsInsideAnExportedFile()
    {
        // The name lives on a registry row keyed by a thread GUID. An exported file lands on a machine that
        // has never heard of that GUID — so if the name rode only on the row, an imported save would wake up
        // as a stranger with the correct purse. It rides in the payload; this is that promise.
        Vault live = VaultAt("The Tilt", docked: true, 192 * 86400, new LogbookSection
        {
            CaptainName = "Captain Erno",
            Title = "day 192, hold full",
            Note = "banked before undocking",
        });

        Vault elsewhere = VaultSerializer.Load(VaultSerializer.Save(live));
        Assert.Equal("Captain Erno", elsewhere.Logbook?.CaptainName);

        // And the import preview can say whose moment it is BEFORE the captain commits to boarding it.
        SaveSlotMeta preview = SaveSlotLabels.PreviewMeta(elsewhere);
        Assert.Equal("Captain Erno", preview.CaptainName);
        Assert.Equal("day 192, hold full", SaveSlotLabels.TitleOf(preview));
        Assert.Equal("banked before undocking", preview.Note);
    }

    // ─────────────────────────────────────────────────────────────────────────────────────────────
    // 3 · THE FEAR — "I want this moment, not that I die and that situation overwrites this."
    // ─────────────────────────────────────────────────────────────────────────────────────────────

    [Fact]
    public void THE_FEAR_DyingDoesNotOverwriteAMomentYouBanked()
    {
        // The owner's exact sequence, played out: bank the good moment, then go and die, then let the rolling
        // autosave do what it does on every durable event afterwards. The banked berth must come back BYTE
        // FOR BYTE — payload and label — no matter how many times the ship saves over its own shoulder.
        var store = new MemStore();
        var book = new SaveSlotBook(store, "universe-3");

        Vault good = VaultAt("The Tilt", docked: true, 192 * 86400, new LogbookSection
        {
            CaptainName = "Captain Erno",
            Title = "THE moment — hold full, purse fat",
            Note = "Do not lose this one.",
        });
        string goodPayload = VaultSerializer.Save(good);
        SaveSlotMeta goodMeta = MetaFor(good, SaveSlotKind.Manual, ticks: 1_000);
        book.Save(SaveSlotBook.ManualSlotId(4), goodPayload, goodMeta);

        // …and now the run goes wrong. Every one of these is a durable event writing the rolling autosave.
        for (int i = 1; i <= 25; i++)
        {
            Vault worse = VaultAt("Luna", docked: false, (192 + i) * 86400, new LogbookSection
            {
                CaptainName = "Captain Erno",
            });
            book.Save(SaveSlotBook.AutoSlotId, VaultSerializer.Save(worse), MetaFor(worse, SaveSlotKind.Autosave, 2_000 + i));
        }

        // The moment is exactly as it was left.
        Assert.Equal(goodPayload, book.ReadPayload(SaveSlotBook.ManualSlotId(4)));
        SaveSlotMeta stillThere = book.Get(SaveSlotBook.ManualSlotId(4))!;
        // Record equality — every field, not just the title. (Save stamps the row with its own slot id.)
        Assert.Equal(goodMeta with { Id = SaveSlotBook.ManualSlotId(4) }, stillThere);
        Assert.Equal("THE moment — hold full, purse fat", stillThere.Title);
        Assert.Equal(1_000, stillThere.SavedRealTicks);

        // The autosave is its own berth and holds the disaster, as it should — Continue means "where I
        // actually am", and the bank means "the moment I chose". Both are true at once; that is the design.
        Assert.Equal(SaveSlotBook.AutoSlotId, book.Newest()!.Id);
        Assert.Equal("adrift near Luna", book.Get(SaveSlotBook.AutoSlotId)!.Where);

        // And the shelf still lists both, the bank included — a moment you cannot find is a moment you lost.
        Assert.Contains(book.List(), s => s.Id == SaveSlotBook.ManualSlotId(4));
    }

    [Fact]
    public void THE_FEAR_RewritingThePageOfABankDoesNotMoveItEither()
    {
        // The other half: editing a title must not promote a two-week-old bank to the top of "newest first",
        // and must not make it what Continue resumes. (Retitle deliberately leaves the clocks alone.)
        var book = new SaveSlotBook(new MemStore(), "universe-4");

        Vault old = VaultAt("The Tilt", docked: true, 10 * 86400);
        book.Save("2", VaultSerializer.Save(old), MetaFor(old, SaveSlotKind.Manual, ticks: 100));

        Vault now = VaultAt("Selene Gate", docked: true, 50 * 86400);
        book.Save(SaveSlotBook.AutoSlotId, VaultSerializer.Save(now), MetaFor(now, SaveSlotKind.Autosave, ticks: 900));

        book.Retitle("2", "renamed long after the fact", "and annotated");

        Assert.Equal(SaveSlotBook.AutoSlotId, book.Newest()!.Id);
        Assert.Equal(SaveSlotBook.AutoSlotId, book.List()[0].Id);
        Assert.Equal(100, book.Get("2")!.SavedRealTicks);

        // A page written on an EMPTY berth is a no-op, not a phantom row.
        book.Retitle("7", "nothing here", "nor here");
        Assert.Null(book.Get("7"));
    }
}
