﻿using Microsoft.AspNetCore.Components.Web;
using SpaceSails.Core;

namespace SpaceSails.Client.Pages;

// ─────────────────────────────────────────────────────────────────────────────────────────────────
// Map.Logbook — #948 · THE HUMAN HALF OF A SAVE. Split out of Map.Vault.cs, which owns the MACHINE half
// (build the vault, write it, read it back, rehydrate a run) and had grown past this repo's 1500-line
// line. The split is along a real seam, not an arbitrary one: nothing in this file touches the vault
// payload's contents or the sim. It is about the two things the owner asked for and nothing else —
//
//   THE NAME   the captain's own, replacing the seeded roster name ("it solves the issue of forgetting
//              who you are amongst the autogenerated names"), written through GameThreadRegistry.Rename
//              from either of its two doors: the captain's desk and the front-door roster card.
//
//   THE PAGE   a title and a note on a banked or exported moment ("I would like to save this point with
//              a comment field and a captain's name of my whim"), offered by ONE sheet that serves three
//              gestures — bank into a berth, export a file, rewrite the page of a bank already shelved —
//              because all three write the same three strings.
//
// The second half of that sentence — "I want this moment, not that I die and that situation overwrites
// this" — needed no code at all: a banked berth has never been touched by the rolling autosave (#310's
// law). What it needed was to be SAID, which the sheet now does, and PINNED, which IWantThisMomentTests
// now does against the exact sequence he feared.
// ─────────────────────────────────────────────────────────────────────────────────────────────────
public partial class Map
{

    // ── #948 · THE CAPTAIN HAS A NAME OF THEIR OWN. Owner: "Let's have an option to change the name of our
    //    avatar. It solves the issue of forgetting who you are amongst the autogenerated names." The identity
    //    was already editable DATA on the registry row (Touch preserves it across every autosave); this lane
    //    is the door the older comment above promised. ──

    /// <summary>The active captain's display name — the renamed one if they were renamed, else the seeded
    /// roster name. "" before a thread exists. The one reader for the chip, the desk and every vault write.</summary>
    private string ActiveCaptainName
        => ActiveThreadInfo is { } t ? SpaceSails.Core.Captains.For(t).Name : "";

    /// <summary>Rename a captain (any universe's, not only the one at the helm) and make it stick everywhere
    /// the name is shown or stored: the registry row, the live chip, the roster card — and the SAVES, via a
    /// fresh autosave whose payload carries the new name. A blank name puts the generator back.</summary>
    private void RenameCaptain(string threadId, string? name)
    {
        if (string.IsNullOrEmpty(threadId) || Threads.Rename(threadId, name) is not { } row)
        {
            return;
        }

        RefreshThreadList();
        RefreshSlotList();
        if (threadId == _activeThreadId)
        {
            // The live universe: bank the new name into the rolling autosave at once, so Continue and every
            // export from here on say who you actually are rather than who the generator said you were.
            RequestVaultSave();
        }

        ShowPulseMessage($"🪪 The license now reads {SpaceSails.Core.Captains.For(row).Name}.");
        StateHasChanged();
    }

    // The captain-rename input, opened by the ✏ beside a name (at the desk, or on a roster card). One at a
    // time — the id of the thread being renamed, and the text as typed.
    private string? _renamingThreadId;
    private string _renameDraft = "";

    private void BeginRenameCaptain(string threadId)
    {
        _renamingThreadId = threadId;
        _renameDraft = Threads.Get(threadId) is { } t ? SpaceSails.Core.Captains.For(t).Name : "";
    }

    private void CancelRenameCaptain()
    {
        _renamingThreadId = null;
        _renameDraft = "";
    }

    private void CommitRenameCaptain()
    {
        string? id = _renamingThreadId;
        string draft = _renameDraft;
        CancelRenameCaptain();
        if (!string.IsNullOrEmpty(id))
        {
            RenameCaptain(id, draft);
        }
    }

    private void RenameKeyDown(KeyboardEventArgs e)
    {
        if (e.Key == "Enter")
        {
            CommitRenameCaptain();
        }
        else if (e.Key == "Escape")
        {
            CancelRenameCaptain();
        }
    }
    // ─────────────────────────────────────────────────────────────────────────────────────────────
    // #948 · THE PAGE, BEFORE THE BANK. Owner: "I would like to save this point with a comment field and
    // a captain's name of my whim. I want this moment, not that I die and that situation overwrites this."
    //
    // Banking used to be one silent click. It now stops for the two lines that make a save findable a month
    // later: a TITLE (offered pre-filled as "<captain> — <place> — day N", so accepting the default costs
    // one keystroke) and a NOTE about what you were doing. The same sheet serves three gestures, because
    // they write the same page: bank to a berth, export a file, and EDIT the page of a bank already on the
    // shelf. The banked slot is still never touched by the autosave — that law is #310's and is unchanged.
    // ─────────────────────────────────────────────────────────────────────────────────────────────

    /// <summary>What the open bank sheet is about to do.</summary>
    private enum BankPromptKind
    {
        /// <summary>Bank the LIVE moment into <see cref="_bankSlotId"/>.</summary>
        Bank,

        /// <summary>Download the LIVE moment as a .json carrying this page.</summary>
        Export,

        /// <summary>Rewrite the title/note of an ALREADY-banked slot — no new save is taken.</summary>
        Edit,
    }

    private BankPromptKind? _bankPrompt;
    private string _bankSlotId = "";
    private string _bankThreadId = "";
    private string _bankTitle = "";
    private string _bankNote = "";

    /// <summary>The sheet's heading — it must say plainly which of the three acts is about to happen.</summary>
    private string BankPromptHeading => _bankPrompt switch
    {
        BankPromptKind.Export => "⬇ Export this moment",
        BankPromptKind.Edit => $"✎ The page for slot {_bankSlotId}",
        _ => _bankSlotId == SaveSlotBook.AutoSlotId ? "⤓ Bank into the autosave berth" : $"⤓ Bank into slot {_bankSlotId}",
    };

    /// <summary>Open the sheet for banking the live moment into a berth, title pre-filled with the default.</summary>
    private void BeginBankToSlot(string slotId)
    {
        _bankPrompt = BankPromptKind.Bank;
        _bankSlotId = slotId;
        _bankThreadId = _activeThreadId ?? "";
        _bankTitle = SaveSlotLabels.DefaultTitle(ActiveCaptainName, LiveWhereLine(), LiveSimDay());
        _bankNote = "";
    }

    /// <summary>Open the sheet for exporting the live moment to a file.</summary>
    private void BeginExportMoment()
    {
        _bankPrompt = BankPromptKind.Export;
        _bankSlotId = "";
        _bankThreadId = _activeThreadId ?? "";
        _bankTitle = SaveSlotLabels.DefaultTitle(ActiveCaptainName, LiveWhereLine(), LiveSimDay());
        _bankNote = "";
    }

    /// <summary>Open the sheet on an ALREADY-banked slot's page — "editable in place later" (owner). Loads
    /// what is written there now; committing rewrites the label and the payload, and takes no new save.</summary>
    private void BeginEditSlotPage(string threadId, string slotId)
    {
        if (BookFor(threadId).Get(slotId) is not { } meta)
        {
            return;
        }

        _bankPrompt = BankPromptKind.Edit;
        _bankSlotId = slotId;
        _bankThreadId = threadId;
        _bankTitle = SaveSlotLabels.TitleOf(meta);
        _bankNote = meta.Note;
    }

    // Which slot's note is currently open in full. The rows show a note as ONE clamped line (a shelf of ten
    // paragraphs is not a shelf); clicking it opens that one, and only one is ever open — the drawer stays a
    // list you can scan. Keyed "<threadId>/<slotId>" so two captains' slot 3 are different rows.
    private string? _openNoteKey;

    private static string NoteKey(string threadId, string slotId) => $"{threadId}/{slotId}";

    private void ToggleNote(string threadId, string slotId)
    {
        string key = NoteKey(threadId, slotId);
        _openNoteKey = _openNoteKey == key ? null : key;
    }

    private bool NoteIsOpen(string threadId, string slotId) => _openNoteKey == NoteKey(threadId, slotId);

    private void CancelBankPrompt()
    {
        _bankPrompt = null;
        _bankSlotId = "";
        _bankThreadId = "";
        _bankTitle = "";
        _bankNote = "";
    }

    /// <summary>Commit the open sheet: bank, export, or rewrite the page of a shelved bank.</summary>
    private void CommitBankPrompt()
    {
        BankPromptKind? kind = _bankPrompt;
        string slot = _bankSlotId;
        string thread = _bankThreadId;
        string title = _bankTitle;
        string note = _bankNote;
        CancelBankPrompt();

        switch (kind)
        {
            case BankPromptKind.Bank when slot.Length > 0:
                SaveToSlot(slot, title, note);
                break;
            case BankPromptKind.Export:
                ExportVault(title, note);
                break;
            case BankPromptKind.Edit when slot.Length > 0:
                // NOT a save: Retitle rewrites the label and stamps the payload's logbook section, leaving
                // the voyage and its clocks alone — so editing a page does not promote it to "newest".
                BookFor(thread).Retitle(slot, title, note);
                RefreshThreadList();
                RefreshSlotList();
                ShowPulseMessage($"✎ Slot {slot} — the page is rewritten. The voyage in it is untouched.");
                break;
        }

        StateHasChanged();
    }

    // The live WHERE line and sim day, for the default title. Same derivation the slot label uses, read off
    // the live resume section rather than a saved vault, so the offered default names where you ARE.
    private string LiveWhereLine()
    {
        ResumeSection? resume = BuildResumeSection();
        if (resume is null || string.IsNullOrWhiteSpace(resume.HavenName))
        {
            return "unknown waters";
        }

        return resume.WasDocked ? resume.HavenName : $"adrift near {resume.HavenName}";
    }

    private int LiveSimDay() => (int)(_ship.SimTime / 86400);

}
